version: "3.9"

services:
    database:
        image: postgres
        container_name: database_roomly
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=roomly
            - POSTGRES_PASSWORD=apm174dh
            - POSTGRES_DB=roomly
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: roomly
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
